---
- hosts: all
  user: "{{ sudoUser }}"
  sudo: True
  roles:
    - common
  tags: common


- hosts: zookeeper_node
  user: "{{ sudoUser }}"
  sudo: True
  roles:
    - { role: 'ansible-zookeeper',
        zoo_id: '{{ groups.zookeeper_node | get_id_element_by_value(inventory_hostname) }}',
        zookeeper_hosts: "{{ groups.zookeeper_node |array_to_array_of_dicts }}"
      }
  tags:
    - zookeeper

- hosts: mesos_node
  user: "{{ sudoUser }}"
  sudo: True
  roles:
    - { role: 'ansible-mesos',
        zookeeper_hostnames: "{{ groups.zookeeper_node | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}",
        mesos_install_mode: "master-slave"
      }

#mesos_version: "0.25.0 "
#mesos_package_version: "1.0"